system.vpn.management.port=7505
system.vpn.log-dir=/tmp/matchday/vpn-log
system.vpn.auto-start=false
system.vpn.startup-arguments=--verb 11 \
      --auth-user-pass /etc/openvpn/auth.txt \
      --route 192.168.0.0 255.255.255.0 net_gateway \
      --auth-nocache \
      --management localhost ${system.vpn.management.port} \
      --log-append ${system.vpn.log-dir}/openvpn.log \
      --status ${system.vpn.log-dir}/openvpn.status 10 \
      --writepid ${system.vpn.log-dir}/openvpn.pid \
      --daemon matchday-vpn